Repository RvNovae/dhge-latex, pull requests merged in 2020-07, with the labels that each got.

#36 Add icomma package by default
  build/package.config.tex
Labels: enhancement

#35 Change default date to \today
  config.tex
Labels: enhancement

#38 Add standard spacing to mathrm environment
  build/setup.tex
Labels: enhancement

#41 structure changes
  abk.tex
  anlagen.tex
  assets/img/.gitkeep
  build/components/alphabetic-ibid.cbx
  build/components/com.tex
  build/components/deckblatt.tex
  build/components/ehrenwort.tex
  build/components/package.config.tex
  build/components/setup.tex
  build/template.tex
Labels: enhancement

#42 add command doubleunderline
  build/components/com.tex
  build/components/setup.tex
Labels: enhancement

#48 fixed linking bug
  build/template.tex
Labels: bug

#44 automatisches erstellen eines Anlagenverzeichnis
  .gitignore
  build/components/com.tex
  build/template.tex
Labels: enhancement

#47 Automatic tests
  .travis.yml
  build/tests/img.png
  build/tests/main.tex
Labels: Priority-Medium, enhancement
