Repository RvNovae/dhge-latex, pull requests merged in 2022-01, with the labels that each got.

#112 Fix Ehrenwort formatting.
  build/components/ehrenwort.tex
Labels: enhancement

#116 Kusche-Mode-Fix und Seitenzahlen
  README.md
  build/components/setup.tex
  build/template.tex
Labels: bug

#113 Snippets hinzufügen
  .vscode/tex_snippets.code-snippets
  README.md
Labels: documentation, enhancement

#119 Change default figure position
  .vscode/tex_snippets.code-snippets
  README.md
  build/components/com.tex
Labels: enhancement

#121 make parskip configurable
  README.md
  build/components/setup.tex
  build/tests/config.tex
  config.tex
Labels: enhancement
